export const deConfig = {
    0: { name: 'MTI', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    1: { name: 'Bitmap', type: 'Fixo', length:16, unit: 'digits', format: 'ans' },
    2: { name: 'PANX', type: 'LLVAR', length:'bcd', unit: 'digits', format: 'n' },
    3: { name: 'Processing Code', type: 'Fixo', length:6, unit: 'digits', format: 'n' },
    4: { name: 'Amount', type: 'Fixo', length:12, unit: 'digits', format: 'n' },
    5: { name: 'Amount, Settlement', type: 'Fixo', length:12, unit: 'digits', format: 'n' },
    6: { name: 'Amount, Cardholder Billing', type: 'Fixo', length:12, unit: 'digits', format: 'n' },
    7: { name: 'Transmission DT', type: 'Fixo', length:10, unit: 'digits', format: 'n' },
    9: { name: 'Conversion Rate, Settlement', type: 'Fixo', length:8, unit: 'digits', format: 'n' },
    10: { name: 'Conversion Rate, Cardholder Billing', type: 'Fixo', length:8, unit: 'digits', format: 'n' },
    11: { name: 'STAN', type: 'Fixo', length:6, unit: 'digits', format: 'n' },
    12: { name: 'Local Time', type: 'Fixo', length:6, unit: 'digits', format: 'n' },
    13: { name: 'Local Date', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    14: { name: 'Date, Expiration', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    15: { name: 'Date, Settlement', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    16: { name: 'Date, Conversion', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    18: { name: 'Merchant Type', type: 'Fixo', length:4, unit: 'digits', format: 'n' },
    19: { name: 'Acquiring Institution Country Code', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    20: { name: 'PAN Extended, Country Code', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    22: { name: 'Point-of-Service Entry Mode Code', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    23: { name: 'Card Sequence Number', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    25: { name: 'Point-of-Service Condition Code', type: 'Fixo', length:2, unit: 'digits', format: 'n' },
    26: { name: 'Point-of-Service PIN Capture Code', type: 'Fixo', length:2, unit: 'digits', format: 'n' },
    28: { name: 'Amount, Transaction Fee', type: 'Fixo', length:8, unit: 'digits', format: 'n' },
    30: { name: 'amount, Settlemtn Fee', type: 'Fixo', length:8, unit: 'digits', format: 'n' },
    32: { name: 'Acquiring Institution Identification Code', type: 'LLVAR', length:'bcd', unit: 'digits', format: 'n' },
    33: { name: 'Forwarding Institution Identification Code', type: 'LLVAR', length:'bcd', unit: 'digits', format: 'n'},
    34: { name: 'Acceptance Environment Data (TLV Format)', type: 'LLLVAR', length:'bcd', unit: 'digits', format: 'b' },
    35: { name: 'Track 2 Data', type: 'LLVAR', length:'bcd', unit: 'digits', format: 'n' },
    37: { name: 'Retrieval Reference Number', type: 'Fixo', length:12, unit: 'digits', format: 'e' },
    38: { name: 'Authorization Identification Response', type: 'Fixo', length:6, unit: 'digits', format: 'n' },
    39: { name: 'Response Code', type: 'Fixo', length:2, unit: 'digits', format: 'e' },
    41: { name: 'Terminal ID', type: 'Fixo', length:8, unit: 'digits', format: 'e' },
    42: { name: 'Card Acceptor Identification Code', type: 'Fixo', length:15, unit: 'digits', format: 'e' },
    43: { name: 'Card Acceptor Name/Location', type: 'Fixo', length:40, unit: 'digits', format: 'e' },
    44: { name: 'Additional Response Data', type: 'LLVAR', length:'bcd', unit: 'bytes', format: 'e' },
    45: { name: 'Track 1 Data', type: 'LLVAR', length:77, unit: 'digits', format: 'ans' },
    46: { name: 'Expanded Additional Amounts', type: 'LLLVAR', length:'bcd', unit: 'digits', format: 'ans' },
    48: { name: 'Additional Data—Private', type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdic"},
    49: { name: 'Currency Code', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    50: { name: 'Currency Code, Sett', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    51: { name: 'Currency Code, Cardholder Billing', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    52: { name: 'PIN Block', type: 'Fixo', length:8, unit: 'bytes', format: 'bin' },
    53: { name: 'Security-Related Control Information', type: 'Fixo', length:16, unit: 'digits', format: 'n' },
    54: { name: 'Additional Amounts', type: 'LLLVAR', length:'bcd', unit: 'digits', format: 'ans' },
    55: { name: 'ICC Data', type: 'var', lengthType:'binary', lengthBytes: 2, unit: 'bytes', maxLength: 255, format: 'bin', COMPLEX: true },
    56: { name: 'Customer Related Data', type: 'LLLVAR', length:'bcd', unit: 'digits', format: 'ans' },
    58: { name: 'National POS Geographic Data', type: 'LLVAR', length:60, unit: 'digits', format: 'ans' },
    59: { name: 'National POS Geographic Data', type: 'LLVAR', length:'binary', unit: 'bytes', format: 'e' },
    60: { name: 'Additional POS Information', type: 'LLVAR', length:'binary', unit: 'bytes', format: 'n' },
    61: { name: 'Other Amount, Transaction', type: 'LLVAR', length:'binary', unit: 'bytes', format: 'a' },
    62: { name: 'Custom Payment Service',  type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    63: { name: 'VIP Private-Use Field', type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    64: { name: 'Message Authentication Code', type: 'Fixo', length:8, unit: 'bytes', format: 'bin' },
    70: { name: 'Network Management Information Code', type: 'Fixo', length:3, unit: 'digits', format: 'n' },
    73: { name: 'Date, Action', type: 'Fixo', length:6, unit: 'digits', format: 'ans' },
    90: { name: 'Original Data Elements', type: 'Fixo', length:21, unit: 'digits', format: 'n' },
    91: { name: 'File Update Code', type: 'Fixo', length:1, unit: 'digits', format: 'ans' },
    92: { name: 'File Security Code', type: 'Fixo', length:2, unit: 'digits', format: 'ans' },
    95: { name: 'Replacement Amounts', type: 'Fixo', length:42, unit: 'digits', format: 'ans' },
    96: { name: 'Reserved for Future Use', type: 'Fixo', length:64, unit: 'digits', format: 'ans' },
    100: { name: 'Receiving Institution Identification Code', type: 'LLVAR', length:11, unit: 'digits', format: 'ans' },
    101: { name: 'File Name', type:'var', lengthType: 'binary', lengthBytes: 1, maxLength: 17, unit: 'bytes', format: 'e', encoding: 'ebcdic'},
    102: { name: 'Account Identification 1', type: 'LLVAR', length:29, unit: 'digits', format: 'ans' },
    104: { name: 'Transaction Description and Transaction-Specific Data', type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    105: { name: 'Double-Length DES Key (Triple DES)', type: 'Fixo', length:128, unit: 'digits', format: 'ans' },
    106: { name: 'Fleet Service Data', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    107: { name: 'Reserved for Future Use', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    108: { name: 'Data in Local Language', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    110: { name: 'Encryption Data (TLV Format)', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    111: { name: 'Additional Transaction Specific Data (TLV Format)', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    112: { name: 'Additional Data [National Use', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    114: { name: 'Domestic and Localized Data (TLV Format)', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    120: { name: 'Auxiliary Transaction Data', type: 'LLLVAR', length:9999, unit: 'digits', format: 'ans' },
    121: { name: 'Issuing Institution Identification Code', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    122: { name: 'Reserved for Future Use', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    123: { name: 'Reserved for Future Use', type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    124: { name: 'Reserved for Future Use', type: 'LLLVAR', length:999, unit: 'digits', format: 'ans' },
    125: { name: 'Supporting Information',  type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    126: { name: 'Private Data', type: 'LLLVAR', length:'binary', unit: 'bytes', format: 'n' },
    127: { name: 'Private Data', type: 'var', lengthType:'binary', lengthBytes: 1, unit: 'bytes', maxLength: 255, encoding: "ebcdicHEX", COMPLEX: true},
    128: { name: 'MAC', type: 'Fixo', length:16, unit: 'digits', format: 'ans' } 
};
